/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package project2;

import org.junit.jupiter.api.Test;

import com.ncr.plugins.SimplePlugin;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        SimplePlugin classUnderTest = new SimplePlugin();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
