/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ncr.plugins;
import org.gradle.api.Plugin;
import org.gradle.api.Project;

public class SimplePlugin implements Plugin<Project>{
    public String getGreeting() {
        return "Hello World p2 included!";
    }

	@Override
	public void apply(Project arg0) {
		// TODO Auto-generated method stub
		
	}

	

    
}
